---
proxy-providers:
  Gaming:
    type: file
    path: "./proxy_provider/gaming.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Sosmed:
    type: file
    path: "./proxy_provider/sosmed.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Streaming:
    type: file
    path: "./proxy_provider/streaming.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Browsing:
    type: file
    path: "./proxy_provider/browsing.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: Gaming
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Gaming
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Sosmed
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Sosmed
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Streaming
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Streaming
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Browsing
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Browsing
  url: http://www.gstatic.com/generate_204
  interval: '300'
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: onk
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  nameserver:
  - 192.168.8.1
  - dhcp://"eth1"
  default-nameserver:
  - 192.168.8.1
ipv6: false
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
profile:
  store-selected: true
rules:
- RULE-SET,Gaming,Gaming
- RULE-SET,Sosmed,Sosmed
- RULE-SET,Streaming,Streaming
- RULE-SET,Direct,DIRECT
- RULE-SET,Reject,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- MATCH,GLOBAL
rule-providers:
  Reject:
    type: file
    behavior: classical
    path: "./rule_provider/reject.yaml"
  Direct:
    type: file
    behavior: classical
    path: "./rule_provider/direct.yaml"
  Sosmed:
    type: file
    behavior: classical
    path: "./rule_provider/sosmed.yaml"
  Gaming:
    type: file
    behavior: classical
    path: "./rule_provider/gaming.yaml"
  Streaming:
    type: file
    behavior: classical
    path: "./rule_provider/streaming.yaml"
